# Generated by Django 6.0.4 on 2026-04-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=200, verbose_name='Type de produit')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valeur (CAD)')),
                ('is_perishable', models.BooleanField(default=False, verbose_name='Périssable')),
                ('is_dangerous', models.BooleanField(default=False, verbose_name='Matière dangereuse')),
                ('hs_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code HS')),
                ('weight_kg', models.FloatField(blank=True, null=True, verbose_name='Poids total (kg)')),
                ('volume_m3', models.FloatField(blank=True, null=True, verbose_name='Volume total (m3)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
