# Generated by Django 6.0.4 on 2026-04-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0003_alter_country_options_remove_country_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('company_type', models.CharField(choices=[('BANNER', 'Bannière / Siège Social'), ('BRANCH', 'Succursale / Magasin'), ('INDEPENDENT', 'Indépendante / Compagnie à numéro')], default='INDEPENDENT', max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='NEQ / No. Entreprise')),
                ('is_billing_center', models.BooleanField(default=True, verbose_name='Centre de facturation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='addresses.address', verbose_name='Adresse principale')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company', verbose_name='Entreprise parente (Bannière)')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
    ]
