# Generated by Django 6.0.4 on 2026-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_alter_country_options_remove_country_name_en_and_more'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_synthetic',
            field=models.BooleanField(default=False, verbose_name='Créé automatiquement'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company_type', 'BRANCH'), _negated=True), ('parent__isnull', False), _connector='OR'), name='branch_must_have_parent'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company_type__in', ['BANNER', 'INDEPENDENT']), _negated=True), ('parent__isnull', True), _connector='OR'), name='banner_and_independent_must_not_have_parent'),
        ),
    ]
