# Generated by Django 6.0.4 on 2026-04-23 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_is_synthetic_company_branch_must_have_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_company', models.CharField(choices=[('OWNER', 'Propriétaire'), ('BUYER', "Acheteur / Donneur d'ordre"), ('EMPLOYEE', 'Employé'), ('ACCOUNTING', 'Comptabilité')], default='EMPLOYEE', max_length=20)),
                ('is_primary', models.BooleanField(default=False, verbose_name='Unité principale')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliation Entreprise',
                'verbose_name_plural': 'Affiliations Entreprises',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
