# Generated by Django 6.0.4 on 2026-04-23 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom (FR)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Nom (EN)')),
                ('iso2', models.CharField(max_length=2, unique=True, verbose_name='Code ISO 2')),
                ('iso3', models.CharField(max_length=3, unique=True, verbose_name='Code ISO 3')),
                ('is_active', models.BooleanField(default=True, verbose_name='Zone desservie')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['name_fr'],
            },
        ),
        migrations.AddField(
            model_name='address',
            name='country_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='addresses.country'),
        ),
    ]
