# Generated by Django 6.0.4 on 2026-04-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_country_address_country_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Pays', 'verbose_name_plural': 'Pays'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_fr',
        ),
        migrations.AddField(
            model_name='country',
            name='iso_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='ISO 3166-1 (NUM)'),
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default='Unknown', max_length=200, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='country',
            name='sovereignty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Souveraineté'),
        ),
        migrations.AddField(
            model_name='country',
            name='subdivision_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subdivision Code'),
        ),
        migrations.AddField(
            model_name='country',
            name='tld',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='TLD'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(max_length=2, unique=True, verbose_name='ISO 3166-1 (A-2)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(max_length=3, unique=True, verbose_name='ISO 3166-1 (A-3)'),
        ),
    ]
