# Generated by Django 6.0.4 on 2026-04-22 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='equipment_types',
            field=models.ManyToManyField(blank=True, related_name='quotes', to='quotes.equipmenttype'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='final_drop_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_as_drop', to='addresses.address'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='pick_up_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_as_pickup', to='addresses.address'),
        ),
    ]
