# Generated by Django 6.0.4 on 2026-04-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de livraison souhaitée'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de ramassage souhaitée'),
        ),
    ]
