# Generated by Django 6.0.4 on 2026-04-22 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('quotes', '0003_quoterequest_delivery_date_quoterequest_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='incoterm',
            field=models.CharField(blank=True, choices=[('EXW', 'EXW - Ex Works'), ('FCA', 'FCA - Free Carrier'), ('CPT', 'CPT - Carriage Paid To'), ('CIP', 'CIP - Carriage and Insurance Paid To'), ('DAP', 'DAP - Delivered At Place'), ('DPU', 'DPU - Delivered at Place Unloaded'), ('DDP', 'DDP - Delivered Duty Paid'), ('FAS', 'FAS - Free Alongside Ship'), ('FOB', 'FOB - Free On Board'), ('CFR', 'CFR - Cost and Freight'), ('CIF', 'CIF - Cost, Insurance and Freight')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='products.product'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
