# Generated by Django 6.0.4 on 2026-04-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quoterequest_incoterm_quoterequest_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='estimated_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='estimated_duration_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
