# Generated by Django 6.0.4 on 2026-04-23 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_alter_country_options_remove_country_name_en_and_more'),
        ('companies', '0004_migrate_user_company_to_membership'),
        ('products', '0001_initial'),
        ('quotes', '0005_quoterequest_estimated_distance_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='assigned_employee',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='client_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='equipment_types',
            field=models.ManyToManyField(blank=True, to='quotes.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='final_drop_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_drop', to='addresses.address'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='incoterm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='pick_up_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes_pickup', to='addresses.address'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote', to='products.product'),
        ),
    ]
