# Generated by Django 6.0.4 on 2026-04-22 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0004_quoterequest_incoterm_quoterequest_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_response', models.JSONField(verbose_name="Réponse brute de l'IA (JSON)")),
                ('model_version', models.CharField(default='gemini-1.5-flash', max_length=50, verbose_name='Version du modèle IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='quotes.quoterequest', verbose_name='Soumission associée')),
            ],
            options={
                'verbose_name': 'Analyse de Soumission',
                'verbose_name_plural': 'Analyses de Soumissions',
            },
        ),
    ]
